### ISSUE TITLE
Replication status 0% upon full replication?

### ISSUE THREAD

**Issue by chartgerink** [geut/permanent-seeder#102]
While debugging the Hypergraph application, @juliangruber and I stumbled upon something in the permanent seeder. 

Specifically, where the Hyperdrive was replicated (only containing an `index.json`) but the replication state was at 0%. It seemed like the replication was instead at 100%.

[This line](https://github.com/geut/permanent-seeder/blob/284cc039dcaa2bb4a51b0683a75dae33fcad3a9f/packages/dashboard/src/components/DriveItem.js#L148) calculates the download percentage, and we wondered whether the 0% might be an artifact because there are 0 blocks? Here, `0 / (0 || 1) = 0%` but in this scenario it could be seen as a complete replication?

This is not a crucial issue; wanted to note it for tracking.

**Comment by estebanprimost** [comment]
Hi @chartgerink! thanks for your comment. 
- Situation 1: `downloadedBlocks = 0` **AND** `sizeBlocks = 0`: no way to show some value. This shouldn't happen anyways.
- Situation 2:  `downloadedBlocks = 0` **OR** `sizeBlocks = 0`: here we can use the only value present to show `100%` download.

Makes sense?

btw, how do you know that is fully replicated? Do you see some other value around or it's just a file system check?

**Comment by juliangruber** [comment]
> btw, how do you know that is fully replicated? Do you see some other value around or it's just a file system check?

We looked at the index.json metadata, which was up to data, but at the same time `index.json` wasn't shown as a file and it was at 0%, although everything had already been downloaded

**Comment by dpaez** [comment]
this should be fixed with #130
