### ISSUE TITLE
Update: Auto-delete any removed Hyperdrives upon fetch

### ISSUE THREAD

**Issue by dpaez** [geut/permanent-seeder#155]

**Comment by chartgerink** [comment]
Currently the `endpoint-hook.js` is about adding information to the permanent seeder, and never removes information. This could mean that if the endpoint goes from 10 to 1 module, the permanent-seeder will still include the original 10. For example if at `t1` the endpoint gives as result:

```
module01
module02
module03
module04
module05
module06
module07
module08
module09
module10
```

and at `t2` 

```
module04
```

the permanent seeder would delete all except `module04` at `t2`. This would need to have some failsafes to make sure that it only does so when the request completes properly, to prevent accidental deletion of modules.

What would be a good strategy to address this? The endpoint might give a `200` code but with improper data, and that shouldn't delete the information. Maybe we could do a staged deletion, where modules get slated for deletion when it doesn't return at `t2` and then is actually deleted 10 days later, iff at that time it is still removed?

**Comment by chartgerink** [comment]
@dpaez and I just had a good chat about this. This is a reportback of that conversation.

We are inclined to go for a new route that the permanent seeder consumes that has the deletion keys (if the installer so chooses; `delete-route`). That route is consumed at the same time as the list of keys to add to the permanent seeder (`add-route`). There are several scenarios that can occur as a result, with their respective outcomes sketched out below in a logic table (thumbs up is key present in that condition, thumbs down is key not present):

| `add-route` | `delete-route` | Seed |
|-------------|----------------|------|
| 👍           | 👎              | ✅    |
| 👍           | 👍              | 🚫    |
| 👎           | 👍              | 🚫    |
| 👎           | 👎              | 🚫  (albeit redundant)  |

This is the minimal logic needed to implement deletion from the permanent seeder in a controlled way, as my previous proposal required additional logic about marking for deletion.
