### ISSUE TITLE
socket.io connection refused

### ISSUE THREAD

**Issue by juliangruber** [geut/permanent-seeder#99]
![image](https://user-images.githubusercontent.com/10247/93208581-13893600-f75d-11ea-9b32-0d122dbefb32.png)

The connection is refused and the page stays empty, but the log output doesn't say why

**Comment by juliangruber** [comment]
The drives request stays pending:

![image](https://user-images.githubusercontent.com/10247/93208697-3fa4b700-f75d-11ea-83a9-bfe592a97022.png)

**Comment by juliangruber** [comment]
The only thing I did was manually add a key through the dashboard. The devtools went into the debugger and after reloading the above happens (http://46.101.192.138:3001/#/dashboard). I also updated the vault endpoint to https://vault.hypergraph.xyz/api/modules.

**Comment by estebanprimost** [comment]
- This is a local deployment?
- Have you configured the `.env` on `dashboard` package? You should have `PUBLIC_URL=http://46.101.192.138:3001/` for ubuntu machine. 
- I see `api/drives` is pending (`http://46.101.192.138:3001/api/drives`) checking now

**Comment by juliangruber** [comment]
> * This is a local deployment?

THis is the machine you have access to: http://46.101.192.138:3001/#/dashboard

> * Have you configured the `.env` on `dashboard` package? You should have `PUBLIC_URL=http://46.101.192.138:3001/` for ubuntu machine.

The machine was in the state you left it, then I changed the endpoint url and restarted the service, and everything was still working, then I manually added a key and things broke. It could be that the manually added key was already in the db.

**Comment by estebanprimost** [comment]
Yes, I see that something is blocked between drives being seeded and new keys. We are digging into it.
